In [1]:
!pip install folium
!pip install plotly

Requirement already satisfied: folium in d:\anaconda3\envs\tensorflow\lib\site-packages (0.11.0)
Requirement already satisfied: numpy in d:\anaconda3\envs\tensorflow\lib\site-packages (from folium) (1.18.1)
Requirement already satisfied: branca>=0.3.0 in d:\anaconda3\envs\tensorflow\lib\site-packages (from folium) (0.4.1)
Requirement already satisfied: jinja2>=2.9 in d:\anaconda3\envs\tensorflow\lib\site-packages (from folium) (2.11.2)
Requirement already satisfied: requests in d:\anaconda3\envs\tensorflow\lib\site-packages (from folium) (2.23.0)
Requirement already satisfied: MarkupSafe>=0.23 in d:\anaconda3\envs\tensorflow\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Requirement already satisfied: idna<3,>=2.5 in d:\anaconda3\envs\tensorflow\lib\site-packages (from requests->folium) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\anaconda3\envs\tensorflow\lib\site-packages (from requests->folium) (1.25.8)
Requirement already satisfied: chardet<4,>=3.0.2 in d:\anaconda3\envs\tensorflow\lib\site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\tensorflow\lib\site-packages (from requests->folium) (2020.4.5.1)
Requirement already satisfied: plotly in d:\anaconda3\envs\tensorflow\lib\site-packages (4.8.1)
Requirement already satisfied: retrying>=1.3.3 in d:\anaconda3\envs\tensorflow\lib\site-packages (from plotly) (1.3.3)
Requirement already satisfied: six in d:\anaconda3\envs\tensorflow\lib\site-packages (from plotly) (1.15.0)

In [2]:
# imports
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots

import folium


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


%matplotlib inline

import math
import random 
from datetime import timedelta

import warnings
warnings.filterwarnings('ignore')


#color pallette
cnf = '#393e46'
dth = '#ff2e63'
rec = '#21bf73'
act = '#fe9801'

In [3]:
import plotly as py
py.offline.init_notebook_mode(connected = True)

In [4]:
df=pd.read_csv('C:/Users/Dell/Desktop/Data Work/Covid-19-Preprocessed-Dataset/preprocessed/covid_19_data_cleaned.csv', parse_dates=['Date'])


country_daywise=pd.read_csv('C:/Users/Dell/Desktop/Data Work/Covid-19-Preprocessed-Dataset/preprocessed/country_daywise.csv', parse_dates=['Date'])
countrywise=pd.read_csv('C:/Users/Dell/Desktop/Data Work/Covid-19-Preprocessed-Dataset/preprocessed/countrywise.csv')
daywise=pd.read_csv('C:/Users/Dell/Desktop/Data Work/Covid-19-Preprocessed-Dataset/preprocessed/daywise.csv', parse_dates=['Date'])

In [5]:
df

,Date,Province/State,Country,Lat,Long,Confirmed,Recovered,Deaths,Active
0,2020-01-22,NaN,Afghanistan,33.000000,65.000000,0,0,0,0
1,2020-01-23,NaN,Afghanistan,33.000000,65.000000,0,0,0,0
2,2020-01-24,NaN,Afghanistan,33.000000,65.000000,0,0,0,0
3,2020-01-25,NaN,Afghanistan,33.000000,65.000000,0,0,0,0
4,2020-01-26,NaN,Afghanistan,33.000000,65.000000,0,0,0,0
...,...,...,...,...,...,...,...,...,...
36244,2020-05-25,NaN,Tajikistan,38.861034,71.276093,0,1395,0,-1395
36245,2020-05-26,NaN,Tajikistan,38.861034,71.276093,0,1417,0,-1417
36246,2020-05-27,NaN,Tajikistan,38.861034,71.276093,0,1575,0,-1575
36247,2020-05-28,NaN,Tajikistan,38.861034,71.276093,0,1674,0,-1674
36248,2020-05-29,NaN,Tajikistan,38.861034,71.276093,0,1769,0,-1769

In [6]:
df['Province/State']=df['Province/State'].fillna("")
df

,Date,Province/State,Country,Lat,Long,Confirmed,Recovered,Deaths,Active
0,2020-01-22,,Afghanistan,33.000000,65.000000,0,0,0,0
1,2020-01-23,,Afghanistan,33.000000,65.000000,0,0,0,0
2,2020-01-24,,Afghanistan,33.000000,65.000000,0,0,0,0
3,2020-01-25,,Afghanistan,33.000000,65.000000,0,0,0,0
4,2020-01-26,,Afghanistan,33.000000,65.000000,0,0,0,0
...,...,...,...,...,...,...,...,...,...
36244,2020-05-25,,Tajikistan,38.861034,71.276093,0,1395,0,-1395
36245,2020-05-26,,Tajikistan,38.861034,71.276093,0,1417,0,-1417
36246,2020-05-27,,Tajikistan,38.861034,71.276093,0,1575,0,-1575
36247,2020-05-28,,Tajikistan,38.861034,71.276093,0,1674,0,-1674
36248,2020-05-29,,Tajikistan,38.861034,71.276093,0,1769,0,-1769

In [7]:
country_daywise.tail(15)

,Date,Country,Confirmed,Deaths,Recovered,Active,New Cases,New Deaths,New Recovered
24237,2020-05-09,Turkey,137115,3739,89480,43896,1546,50,3084
24238,2020-05-09,US,1309550,78795,212534,1018221,25621,1615,13541
24239,2020-05-09,Uganda,116,0,55,61,15,0,0
24240,2020-05-09,Ukraine,14710,376,2909,11425,515,15,203
24241,2020-05-09,United Arab Emirates,17417,185,4295,12937,624,11,458
24242,2020-05-09,United Kingdom,216525,31662,1001,183862,3896,346,4
24243,2020-05-09,Uruguay,702,18,513,171,8,0,7
24244,2020-05-09,Uzbekistan,2349,10,1846,493,24,0,71
24245,2020-05-09,Venezuela,402,10,190,202,14,0,0
24246,2020-05-09,Vietnam,288,0,241,47,0,0,0
24247,2020-05-09,West Bank and Gaza,375,2,228,145,0,0,0
24248,2020-05-09,Western Sahara,6,0,5,1,0,0,0
24249,2020-05-09,Yemen,34,7,1,26,0,0,0
24250,2020-05-09,Zambia,252,7,112,133,85,3,1
24251,2020-05-09,Zimbabwe,35,4,9,22,1,0,0

In [8]:
countrywise.head(6)

,Country,Confirmed,Deaths,Recovered,Active,New Cases,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Population,Cases / Million People,Confirmed last week,1 week change,1 week % increase
0,Afghanistan,4033,115,502,3416,255,2.85,12.45,22.91,38928341,104.0,9216,4443,48.21
1,Albania,856,31,627,198,6,3.62,73.25,4.94,2877800,297.0,981,118,12.03
2,Algeria,5558,494,2546,2518,189,8.89,45.81,19.40,43851043,127.0,7918,1216,15.36
3,Andorra,754,48,545,161,2,6.37,72.28,8.81,77265,9759.0,762,2,0.26
4,Angola,43,2,13,28,0,4.65,30.23,15.38,32866268,1.0,60,21,35.00
5,Antigua and Barbuda,25,3,19,3,0,12.00,76.00,15.79,97928,255.0,25,0,0.00

In [9]:
daywise.head(10)

,Date,Confirmed,Deaths,Recovered,Active,New Cases,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,No. of Countries
0,2020-01-22,555,17,28,510,0,3.06,5.05,60.71,6
1,2020-01-23,654,18,30,606,99,2.75,4.59,60.00,8
2,2020-01-24,941,26,36,879,287,2.76,3.83,72.22,9
3,2020-01-25,1434,42,39,1353,493,2.93,2.72,107.69,11
4,2020-01-26,2118,56,52,2010,684,2.64,2.46,107.69,13
5,2020-01-27,2927,82,61,2784,809,2.80,2.08,134.43,16
6,2020-01-28,5578,131,107,5340,2651,2.35,1.92,122.43,16
7,2020-01-29,6166,133,126,5907,588,2.16,2.04,105.56,18
8,2020-01-30,8234,171,143,7920,2068,2.08,1.74,119.58,20
9,2020-01-31,9927,213,222,9492,1693,2.15,2.24,95.95,24

In [10]:
Confirmed = df.groupby('Date').sum()['Confirmed'].reset_index()
Confirmed

          Date  Confirmed
0   2020-01-22        555
1   2020-01-23        654
2   2020-01-24        941
3   2020-01-25       1434
4   2020-01-26       2118
..         ...        ...
124 2020-05-25    5495061
125 2020-05-26    5589626
126 2020-05-27    5691790
127 2020-05-28    5808946
128 2020-05-29    5924275

[129 rows x 2 columns]

In [11]:
Recovered = df.groupby('Date').sum()['Recovered'].reset_index()
Recovered

          Date  Recovered
0   2020-01-22         28
1   2020-01-23         30
2   2020-01-24         36
3   2020-01-25         39
4   2020-01-26         52
..         ...        ...
124 2020-05-25    2231738
125 2020-05-26    2286956
126 2020-05-27    2350088
127 2020-05-28    2415960
128 2020-05-29    2493535

[129 rows x 2 columns]

In [12]:
Deaths = df.groupby('Date').sum()['Deaths'].reset_index()
Deaths

          Date  Deaths
0   2020-01-22      17
1   2020-01-23      18
2   2020-01-24      26
3   2020-01-25      42
4   2020-01-26      56
..         ...     ...
124 2020-05-25  346231
125 2020-05-26  350452
126 2020-05-27  355628
127 2020-05-28  360308
128 2020-05-29  364867

[129 rows x 2 columns]

In [13]:
df['Province/State']=df['Province/State'].fillna("")
df

,Date,Province/State,Country,Lat,Long,Confirmed,Recovered,Deaths,Active
0,2020-01-22,,Afghanistan,33.000000,65.000000,0,0,0,0
1,2020-01-23,,Afghanistan,33.000000,65.000000,0,0,0,0
2,2020-01-24,,Afghanistan,33.000000,65.000000,0,0,0,0
3,2020-01-25,,Afghanistan,33.000000,65.000000,0,0,0,0
4,2020-01-26,,Afghanistan,33.000000,65.000000,0,0,0,0
...,...,...,...,...,...,...,...,...,...
36244,2020-05-25,,Tajikistan,38.861034,71.276093,0,1395,0,-1395
36245,2020-05-26,,Tajikistan,38.861034,71.276093,0,1417,0,-1417
36246,2020-05-27,,Tajikistan,38.861034,71.276093,0,1575,0,-1575
36247,2020-05-28,,Tajikistan,38.861034,71.276093,0,1674,0,-1674
36248,2020-05-29,,Tajikistan,38.861034,71.276093,0,1769,0,-1769

In [14]:
df.isnull().sum()

Date              0
Province/State    0
Country           0
Lat               0
Long              0
Confirmed         0
Recovered         0
Deaths            0
Active            0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36249 entries, 0 to 36248
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            36249 non-null  datetime64[ns]
 1   Province/State  36249 non-null  object
 2   Country         36249 non-null  object
 3   Lat             36249 non-null  float64
 4   Long            36249 non-null  float64
 5   Confirmed       36249 non-null  int64
 6   Recovered       36249 non-null  int64
 7   Deaths          36249 non-null  int64
 8   Active          36249 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(4), object(2)
memory usage: 2.5+ MB

In [16]:
df.query('Country == "US"').tail(8)

,Date,Province/State,Country,Lat,Long,Confirmed,Recovered,Deaths,Active
29146,2020-05-22,,US,37.0902,-95.7129,1600937,350135,95978,1154824
29147,2020-05-23,,US,37.0902,-95.7129,1622612,361239,97086,1164287
29148,2020-05-24,,US,37.0902,-95.7129,1643246,366736,97719,1178791
29149,2020-05-25,,US,37.0902,-95.7129,1662302,379157,98219,1184926
29150,2020-05-26,,US,37.0902,-95.7129,1680913,384902,98912,1197099
29151,2020-05-27,,US,37.0902,-95.7129,1699176,391508,100417,1207251
29152,2020-05-28,,US,37.0902,-95.7129,1721753,399991,101616,1220146
29153,2020-05-29,,US,37.0902,-95.7129,1746019,406446,102809,1236764

In [17]:
Confirmed.tail()

          Date  Confirmed
124 2020-05-25    5495061
125 2020-05-26    5589626
126 2020-05-27    5691790
127 2020-05-28    5808946
128 2020-05-29    5924275

In [18]:
Recovered.tail()

          Date  Recovered
124 2020-05-25    2231738
125 2020-05-26    2286956
126 2020-05-27    2350088
127 2020-05-28    2415960
128 2020-05-29    2493535

In [19]:
Deaths.tail()

          Date  Deaths
124 2020-05-25  346231
125 2020-05-26  350452
126 2020-05-27  355628
127 2020-05-28  360308
128 2020-05-29  364867

In [20]:
import matplotlib.pyplot as plt
fig = go.Figure()
fig.add_trace(go.Scatter(x = Confirmed['Date'], y=Confirmed['Confirmed'], name='Confirmed'))
fig.add_trace(go.Scatter(x = Recovered['Date'], y=Recovered['Recovered'], name='Recovered'))
fig.add_trace(go.Scatter(x = Deaths['Date'], y=Deaths['Deaths'], name='deaths'))
fig.update_layout(title = 'Covid-19 Cases in the Whole World', xaxis_tickfont_size = 14, yaxis = dict(title = 'Number of Covid-19 Cases'))
fig.show()